import Navbar from "../components/Navbar";
import FeatureCard from "../components/FeatureCard";
import StepCard from "../components/StepCard";
import WhyCard from "../components/WhyCard";

function Home() {
  return (
    <>
      {/* Navbar */}
      <Navbar />

      {/* Hero Section */}
      <section className="min-h-screen bg-slate-900 flex flex-col justify-center items-center text-center px-6">
        <h1 className="text-6xl font-bold text-white leading-tight">
          AI Powered{" "}
          <span className="text-blue-500">Resume Analyzer</span>
        </h1>

        <p className="mt-6 text-gray-300 max-w-2xl text-xl">
          Analyze your resume using AI, improve ATS score, compare with Job
          Descriptions and prepare for interviews.
        </p>

        <div className="mt-10 flex gap-5">
          <button className="bg-blue-600 hover:bg-blue-700 text-white px-8 py-3 rounded-xl transition">
            Get Started
          </button>

          <button className="border border-white text-white hover:bg-white hover:text-black px-8 py-3 rounded-xl transition">
            Upload Resume
          </button>
        </div>
      </section>

      {/* Features */}
      <section
        id="features"
        className="bg-slate-950 py-20 px-10"
      >
        <h2 className="text-4xl text-white font-bold text-center mb-14">
          Features
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          <FeatureCard
            icon="🤖"
            title="AI Resume Analysis"
            description="Analyze your resume using Gemini AI and receive personalized feedback."
          />

          <FeatureCard
            icon="📄"
            title="ATS Score"
            description="Improve your ATS score with keyword optimization and smart suggestions."
          />

          <FeatureCard
            icon="🎯"
            title="JD Matching"
            description="Compare your resume with any Job Description and identify skill gaps."
          />

          <FeatureCard
            icon="💬"
            title="Interview Questions"
            description="Generate personalized interview questions based on your resume."
          />
        </div>
      </section>

      {/* How It Works */}
      <section
        id="how-it-works"
        className="bg-slate-900 py-20 px-10"
      >
        <h2 className="text-4xl text-white font-bold text-center mb-14">
          How It Works
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          <StepCard
            number="1"
            title="Upload Resume"
            description="Upload your resume in PDF format securely."
          />

          <StepCard
            number="2"
            title="AI Analysis"
            description="Gemini AI analyzes your resume and extracts key insights."
          />

          <StepCard
            number="3"
            title="ATS Score"
            description="Get ATS score, keyword suggestions and skill gap analysis."
          />

          <StepCard
            number="4"
            title="Improve Resume"
            description="Apply AI suggestions and prepare confidently for interviews."
          />
        </div>
      </section>

      {/* Why Choose HireMind */}
      <section
        id="why-us"
        className="bg-slate-950 py-20 px-10"
      >
        <h2 className="text-4xl text-white font-bold text-center mb-14">
          Why Choose HireMind AI?
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <WhyCard
            icon="⚡"
            title="Instant Analysis"
            description="Get AI-powered resume insights within seconds."
          />

          <WhyCard
            icon="🎯"
            title="Higher ATS Score"
            description="Optimize your resume with recruiter-friendly suggestions."
          />

          <WhyCard
            icon="🤖"
            title="AI Interview Coach"
            description="Practice personalized interview questions generated by AI."
          />
        </div>
      </section>
    </>
  );
}

export default Home;